Django/ScrumMaster/Scrum/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views
from rest_framework.routers import DefaultRouter
from rest_framework_jwt.views import obtain_jwt_token

app_name = "Scrum"

def_router = DefaultRouter()
def_router.register('scrumusers', views.ScrumUserViewSet)
def_router.register('scrumgoals', views.ScrumGoalViewSet)
def_router.register('scrumprojects', views.ScrumProjectViewSet)
def_router.register('scrumprojectroles', views.ScrumProjectRoleViewSet)
def_router.register(r'scrumsprint', views.SprintViewSet, base_name='scrumsprint')

'''
    path('create-user/', views.create_user, name="create_user"),
    path('init-user/', views.init_user, name="init_user"),
    path('scrum-login/', views.scrum_login, name="scrum_login"),
    path('profile/', views.profile, name="profile"),
    path('scrum-logout/', views.scrum_logout, name="scrum_logout"),
    path('add-goal/', views.add_goal, name="add_goal"),
    path('remove-goal/<int:goal_id>/', views.remove_goal, name="remove_goal"),
    path('move-goal/<int:goal_id>/<int:to_id>/', views.move_goal, name="move_goal"),
'''
    
urlpatterns = [
    url(r'api/', include(def_router.urls)),
    url(r'^api-token-auth/', obtain_jwt_token),
    path(r'create-demo/', views.createDemoUser)
]

Django/ScrumMaster/ScrumMaster/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('scrum/', include('Scrum.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

'''
#Uncomment this on deployment.
urlpatterns += [
    path('courses/', include('Courses.urls')),
    path('', include('home.urls'))
]
'''


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/ScrumMaster/Scrum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage


# Create your models here.

fs = FileSystemStorage(location='/media')

class ScrumProject(models.Model):
    name = models.CharField(max_length=50)
    project_count = models.IntegerField(default=0)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
        
class ScrumUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nickname
    
    class Meta:
        ordering = ['nickname']
        
class ScrumProjectRole(models.Model):
    role = models.CharField(max_length=20)
    user = models.ForeignKey(ScrumUser, on_delete=models.CASCADE)
    project = models.ForeignKey(ScrumProject, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.role

class ScrumDemoProject(models.Model):
    project = models.ForeignKey(ScrumProject, on_delete=models.CASCADE)
    expiration_date = models.DateTimeField()
    
    def __str__(self):
        return expiration_date
        
class ScrumGoal(models.Model):
    visible = models.BooleanField(default=True)
    moveable = models.BooleanField(default=True)
    name = models.TextField()
    status = models.IntegerField(default=-1)
    goal_project_id = models.IntegerField(default=0)
    user = models.ForeignKey(ScrumProjectRole, on_delete=models.CASCADE)
    project = models.ForeignKey(ScrumProject, on_delete=models.CASCADE)
    hours = models.IntegerField(default=-1)
    time_created = models.DateTimeField()
    file = models.ImageField(blank=True, null=True, storage=fs)
    
    '''
    0 = Weekly Goal
    1 = Daily Target
    2 = Verify
    3 = Done
    '''
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-id']
        
class ScrumChatRoom(models.Model):
    name = models.TextField()
    hash = models.CharField(max_length=64)
    
class ScrumChatMessage(models.Model):
    user = models.CharField(max_length=50)
    message = models.TextField()
    room = models.ForeignKey(ScrumChatRoom, on_delete=models.CASCADE)


class ScrumSprint (models.Model):
    created_on = models.DateTimeField()
    ends_on = models.DateTimeField()
    goal_project_id = models.IntegerField(default=0)    

    def __str__(self):
        return self.goal_project_id, self.created_on


class ScrumGoalHistory(models.Model):
    name = models.TextField()
    status = models.IntegerField(default=-1)
    goal_project_id = models.IntegerField(default=0)
    user = models.ForeignKey(ScrumProjectRole, on_delete=models.CASCADE)
    project = models.ForeignKey(ScrumProject, on_delete=models.CASCADE)
    hours = models.IntegerField(default=-1)
    time_created = models.DateTimeField()
    file = models.ImageField(blank=True, null=True)
    goal = models.ForeignKey(ScrumGoal, on_delete=models.CASCADE)
    done_by = models.TextField(blank=True, null=True)
    message = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-id']

Django/ScrumMaster/Scrum/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib import messages
from django.utils.dateparse import parse_datetime
from .models import *
from .serializer import *
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.serializers import ValidationError
from rest_framework.response import Response
from django.core import serializers
from django.core.files.storage import FileSystemStorage
import random
import datetime
import re
import json

# Create your views here.

'''
def create_user(request):
    return render(request, "create_user.html")
    
def init_user(request):
    password = request.POST.get('password', None)
    rtpassword = request.POST.get('rtpassword', None)
    if password != rtpassword:
        messages.error(request, 'Error: Passwords Do Not Match.')
        return HttpResponseRedirect(reverse('Scrum:create_user'))
    user, created = User.objects.get_or_create(username=request.POST.get('username', None))
    if created:
        user.set_password(password)
        group = Group.objects.get(name=request.POST.get('usertype', None))
        group.user_set.add(user)
        user.save()
        scrum_user = ScrumUser(user=user, nickname=request.POST.get('full_name'), age=request.POST.get('age', None))
        scrum_user.save()
        messages.success(request, 'User Created Successfully.')
        return HttpResponseRedirect(reverse('Scrum:create_user'))
    else:
        messages.error(request, 'Error: Username Already Exists.')
        return HttpResponseRedirect(reverse('Scrum:create_user'))
        
def scrum_login(request):
    username = request.POST.get('username', None)
    password = request.POST.get('password', None)
    
    login_user = authenticate(request, username=username, password=password)
    if login_user is not None:
        login(request, login_user)
        return HttpResponseRedirect(reverse('Scrum:profile'))
    else:
        messages.error(request, 'Error: Invalid Credentials.')
        return HttpResponseRedirect(reverse('login'))
        
def profile(request):
    if request.user.is_authenticated:
        username = request.user.username
        user_info = request.user.scrumuser
        role = request.user.groups.all()[0].name
        goal_list = ScrumGoal.objects.order_by('user__nickname', '-id')
        nums = [x for x in range(4)]
        final_list = []
        item_prev = None
        
        for item in goal_list:
            if item.user != item_prev:
                item_prev = item.user
                final_list.append((item, goal_list.filter(user=item.user).count()))
            else:
                final_list.append((item, 0))
                
        context = {'username': username, 'user_info': user_info, 'role': role, 'goal_list': final_list, 'nums_list': nums}
        return render(request, "profile.html", context)
    else:
        messages.error(request, 'Error: Please login first.')
        return HttpResponseRedirect(reverse('login'))
    
def scrum_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))
    
def add_goal(request):
    if request.user.is_authenticated:
        name_goal = request.POST.get('name', None)
        group_name = request.user.groups.all()[0].name
        status_start = 0
        if group_name == 'Admin':
            status_start = 1
        elif group_name == 'Quality Analyst':
            status_start = 2
        goal = ScrumGoal(user=request.user.scrumuser, name=name_goal, status=status_start)
        goal.save()
        messages.success(request, 'Goal Added Successfully.')
        return HttpResponseRedirect(reverse('Scrum:profile'))
    else:
        messages.error(request, 'Error: Please login first.')
        return HttpResponseRedirect(reverse('login'))
        
def remove_goal(request, goal_id):
    if request.user.is_authenticated:
        if request.user.groups.all()[0].name == 'Developer':
            if request.user != ScrumGoal.objects.get(id=goal_id).user.user:
                messages.error(request, 'Permission Denied: Unauthorized Deletion of Goal.')
                return HttpResponseRedirect(reverse('Scrum:profile'))
                
        del_goal = ScrumGoal.objects.get(id=goal_id)
        del_goal.delete()
        messages.success(request, 'Goal Removed Successfully.')
        return HttpResponseRedirect(reverse('Scrum:profile'))
    else:
        messages.error(request, 'Error: Please login first.')
        return HttpResponseRedirect(reverse('login'))
        
def move_goal(request, goal_id, to_id):
    if request.user.is_authenticated:
        goal_item = ScrumGoal.objects.get(id=goal_id)
        group = request.user.groups.all()[0].name
        from_allowed = []
        to_allowed = []
        
        if group == 'Developer':
            if request.user != goal_item.user.user:
                messages.error(request, 'Permission Denied: Unauthorized Movement of Goal.')
                return HttpResponseRedirect(reverse('Scrum:profile'))
        
        if group == 'Owner':
            from_allowed = [0, 1, 2, 3]
            to_allowed = [0, 1, 2, 3]
        elif group == 'Admin':
            from_allowed = [1, 2]
            to_allowed = [1, 2]
        elif group == 'Developer':
            from_allowed = [0, 1]
            to_allowed = [0, 1]
        elif group == 'Quality Analyst':
            from_allowed = [2, 3]
            to_allowed = [2, 3]
            
        if (goal_item.status in from_allowed) and (to_id in to_allowed):
            goal_item.status = to_id
        elif group == 'Quality Analyst' and goal_item.status == 2 and to_id == 0:
            goal_item.status = to_id
        else:
            messages.error(request, 'Permission Denied: Unauthorized Movement of Goal.')
            return HttpResponseRedirect(reverse('Scrum:profile'))
        
        goal_item.save()
        messages.success(request, 'Goal Moved Successfully.')
        return HttpResponseRedirect(reverse('Scrum:profile'))
    else:
        messages.error(request, 'Error: Please login first.')
        return HttpResponseRedirect(reverse('login'))
'''

def createDemoUser(request):
    demo_user = User.objects.create(username='demouser' + str(random.random())[2:])
    demo_user_password = 'demopassword' + str(random.random())[2:]
    demo_user.set_password(demo_user_password)
    demo_user.save()
    
    demo_scrumuser = ScrumUser(user=demo_user, nickname='Demo User')
    demo_scrumuser.save()
    
    demo_project_name = 'Demo Project #' + str(demo_user.pk)
    demo_project = ScrumProject(name=demo_project_name)
    demo_project.save()
    
    demo_projectrole = ScrumProjectRole(role="Owner", user=demo_scrumuser, project=demo_project)
    demo_projectrole.save()
    
    demo_projectdemo = ScrumDemoProject(project=demo_project, expiration_date=datetime.datetime.now() + datetime.timedelta(hours=24))
    demo_projectdemo.save()
    
    return JsonResponse({'username': demo_user.username, 'password': demo_user_password, 'project': demo_project_name})
    
    
class ScrumUserViewSet(viewsets.ModelViewSet):
    queryset = ScrumUser.objects.all()
    serializer_class = ScrumUserSerializer
    
    def create(self, request):
        # Pattern Match For an Email: https://www.regular-expressions.info/email.html
        regex_pattern = re.compile(r'(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)')
        if regex_pattern.match(request.data['email']) == None:
            return JsonResponse({'message': 'Error: Invalid email specified.'})
        if request.data['usertype'] == 'Owner' and ScrumProject.objects.filter(name__iexact=request.data['projname']).count() > 0:
            return JsonResponse({'message': 'Error: That project name is already taken.'})
        if request.data['usertype'] == 'Owner' and len(request.data['projname']) > 50:
            return JsonResponse({'message': 'Error: A project name cannot go over 50 characters.'})
        if len(request.data['full_name']) > 50:
            return JsonResponse({'message': 'Error: A user nickname cannot go over 50 characters.'})
        
        user, created = User.objects.get_or_create(username=request.data['email'], email=request.data['email'])
        if created:
            scrum_user = ScrumUser(user=user, nickname=request.data['full_name'])
            scrum_user.save()
            if request.data['usertype'] == 'Owner':
                scrum_project = ScrumProject(name=request.data['projname'])
                scrum_project.save()
                scrum_project_role = ScrumProjectRole(role="Owner", user=scrum_user, project=scrum_project)
                scrum_project_role.save()

            user.set_password(request.data['password'])
            user.save()
            return JsonResponse({'message': 'User Created Successfully.'})
        else:
            return JsonResponse({'message': 'Error: User with that e-mail already exists.'})

            
def filtered_users(project_id):
    project = ScrumProjectSerializer(ScrumProject.objects.get(id=project_id)).data
    time_check = datetime.datetime.utcnow().replace(tzinfo=None)
    for user in project['scrumprojectrole_set']:
        user['scrumgoal_set'] = [x for x in user['scrumgoal_set'] if x['visible'] == True]
        total_hours = 0
        
        for goal in user['scrumgoal_set']:
            if (time_check - parse_datetime(goal['time_created']).replace(tzinfo=None)).days < 7:
                if goal['hours'] != -1 and goal['status'] == 3:
                    total_hours += goal['hours']
        
        user['total_week_hours'] = total_hours
            
        
    return project['scrumprojectrole_set']


class ScrumProjectViewSet(viewsets.ModelViewSet):

Django/ScrumMaster/Scrum/templates/create_user.html
<h1>Create User</h1>
<form action="{% url 'Scrum:init_user' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username">
    <br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password">
    <br>
    <label for="rtpassword">Retype Password:</label>
    <input type="password" id="rtpassword" name="rtpassword">
    <br>
    <label for="full_name">Full Name:</label>
    <input type="text" id="full_name" name="full_name">
    <br>
    <label for="age">Age:</label>
    <input type="text" id="age" name="age">
    <br>
    <label for="usertype">User Type:</label>
    <select id="usertype" name="usertype">
        <option value="Owner">Owner</option>
        <option value="Admin">Admin</option>
        <option value="Developer" selected="selected">Developer</option>
        <option value="Quality Analyst">Quality Analyst</option>
    </select>
    <br>
    <input type="submit" value="Create User">
</form>

{% if messages %}
    {% for message in messages %}
        <h3>{{message}}</h3>
    {% endfor %}
{% endif %}

<a href="{% url 'login' %}">Back To Login</a>

Django/ScrumMaster/Scrum/templates/profile.html
<h2>Currently Logged in as {{username}} - {{role}}</h2>
<a href="{% url 'Scrum:scrum_logout' %}">Logout</a>
<br>
<h3>Your Details</h3>
<ul>
    <li>Name: {{user_info.nickname}}</li>
    <li>ID: {{user_info.id}}</li>
    <li>Age: {{user_info.age}}</li>
</ul>
<h3>Add Goal</h3>
<form action="{% url 'Scrum:add_goal' %}" method="post">
    {% csrf_token %}
    <label for="name">Name:</label>
    <input type="text" id="name" name="name">
    <br>
    <input type="submit" value="Add Goal">
</form>

{% if messages %}
    {% for message in messages %}
        <h3 style="{% if message.tags == 'success'%} color: green {% else %} color:red {% endif %};">{{message}}</h3>
    {% endfor %}
{% endif %}

<style>
    .full-box {
        text-align: center;
        border: 2px solid black;
        padding: 10px;
    }
    .top-box {
        text-align: center;
        border: 1px solid gray;
        border-top: 2px solid black;
        padding: 10px;
    }
    .reg-box {
        text-align: center;
        border: 1px solid gray;
        padding: 10px;
    }
</style>
{% if goal_list %}
    <table style="table-layout: fixed; width: 700px; word-wrap: break-word; border-collapse: collapse; border: 2px solid black;">
        <tr>
            <th colspan="6" class="full-box">Available Goal{{goal_list|pluralize}}</th>
        </tr>
        <tr>
            <th class="full-box">Created By</th>
            <th class="full-box">Weekly Goal</th>
            <th class="full-box">Daily Target</th>
            <th class="full-box">Verify</th>
            <th class="full-box">Done</th>
            <th class="full-box">Remove</th>
        </tr>
        {% for goal, goal_count in goal_list %}
            <tr>
                {% if goal_count != 0%}
                    <td rowspan="{{goal_count}}" class="full-box">{{goal.user.nickname}}</td>
                {% endif %}
                
                {% for num in nums_list %}
                    <td class="{% if goal_count != 0%} top-box {% else %} reg-box {% endif %}">
                        {% if goal.status == num %}
                            {{goal.id}}) {{goal.name}}
                        {% else %}
                            <a href="{% url 'Scrum:move_goal' goal.id num %}">-</a>
                        {% endif %}
                    </td>
                {% endfor %}
                <td class="{% if goal_count != 0%} top-box {% else %} reg-box {% endif %}">
                    <a href="{% url 'Scrum:remove_goal' goal.id %}">*</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No goals have been created.</p>
{% endif %}